{% set name = "GooseHDF5" %}
{% set org = "tdegeus" %}
{% set version = "0.26.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: bb5ffce2042a87dfd3d7d63f2bfec999a77e2fda246c97ea4afb7d0ce2990572

build:
  number: 0
  noarch: python
  script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - G5compare = GooseHDF5:_G5compare_cli
    - G5list = GooseHDF5:_G5list_cli
    - G5modify = GooseHDF5:_G5modify_cli
    - G5print = GooseHDF5:_G5print_cli

requirements:
  host:
    - pip
    - python >=3
    - setuptools_scm
  run:
    - click
    - h5py
    - numpy
    - prettytable
    - python >=3
    - pyyaml
    - termcolor
    - typing-extensions >=4.5.0

test:
  imports:
    - {{ name }}
  commands:
    - pip check
    - python -c "import {{ name }}; assert {{ name }}.version == '{{ version }}'"
    - G5compare --version
    - G5list --version
    - G5modify --version
    - G5print --version
  requires:
    - pip

about:
  home: https://github.com/{{ org }}/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple tools to inspect HDF5 files (wraps around h5py).
  description: Simple tools to inspect HDF5 files (wraps around h5py).
  doc_url: https://github.com/{{ org }}/{{ name }}
  dev_url: https://github.com/{{ org }}/{{ name }}

extra:
  recipe-maintainers:
    - tdegeus
