{% set name = "GooseHDF5" %}
{% set org = "tdegeus" %}
{% set version = "0.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: afdb8288a13b4301534089790d2ef7aca59b77cb5ea045207c2c5257f8dedb68

build:
  number: 0
  noarch: python
  script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - G5check = GooseHDF5.cli.G5check:main
    - G5compare = GooseHDF5:_G5compare_cli
    - G5list = GooseHDF5:_G5list_cli
    - G5print = GooseHDF5:_G5print_cli
    - G5repack = GooseHDF5.cli.G5repack:main
    - G5repair = GooseHDF5.cli.G5repair:main

requirements:
  host:
    - pip
    - python >=3
    - setuptools_scm
  run:
    - click
    - h5py
    - numpy
    - prettytable
    - python >=3
    - pyyaml
    - termcolor

test:
  imports:
    - {{ name }}
  commands:
    - pip check
    - python -c "import {{ name }}; assert {{ name }}.version == '{{ version }}'"
    - G5check --version
    - G5compare --version
    - G5list --version
    - G5print --version
    - G5repack --version
    - G5repair --version
  requires:
    - pip

about:
  home: https://github.com/{{ org }}/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple tools to inspect HDF5 files (wraps around h5py).
  description: Simple tools to inspect HDF5 files (wraps around h5py).
  doc_url: https://github.com/{{ org }}/{{ name }}
  dev_url: https://github.com/{{ org }}/{{ name }}

extra:
  recipe-maintainers:
    - tdegeus
