{% set name = "goosehdf5" %}
{% set version = "0.9.2" %}
{% set sha256 = "d096404d6e7b4f1706162910830102f50aa605f9276de8ca09bd928c844f7460" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/GooseHDF5/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - G5check = GooseHDF5.cli.G5check:main
    - G5compare = GooseHDF5.cli.G5compare:main
    - G5list = GooseHDF5.cli.G5list:main
    - G5repair = GooseHDF5.cli.G5repair:main

requirements:
  host:
    - python >=3
    - pip
    - setuptools
  run:
    - python >=3
    - docopt
    - h5py

test:
  imports:
    - GooseHDF5
  commands:
    - G5check --help
    - G5compare --help
    - G5list --help
    - G5repair --help

about:
  home: https://github.com/tdegeus/GooseHDF5
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple tools to inspect HDF5 files (wraps around h5py).
  description: Simple tools to inspect HDF5 files (wraps around h5py).
  doc_url: https://github.com/tdegeus/GooseHDF5
  dev_url: https://github.com/tdegeus/GooseHDF5

extra:
  recipe-maintainers:
    - tdegeus
